platform = "android"
target = "template_release"
arch = "arm64"
optimize = "size_extra"
lto = "full"

# Toggles.
production = "yes"
deprecated = "no"
minizip = "no"
brotli = "no"
vulkan = "no"
use_volk = "no"
accesskit = "no"
sdl = "no"
disable_3d = "yes"
disable_advanced_gui = "yes"
disable_physics_2d = "yes"
disable_physics_3d = "yes"
disable_navigation_2d = "yes"
disable_navigation_3d = "yes"
disable_xr = "yes"
engine_update_check = "no"
generate_android_binaries = "yes"
swappy = "yes"

# Modules.
modules_enabled_by_default = "no"
module_freetype_enabled = "yes"
module_gdscript_enabled = "yes"
module_text_server_fb_enabled = "yes"
module_webp_enabled = "yes"
